---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: copy-user
spec:
  type: copy
  secretName: my-username
  secretCopy: copied-secret-2
---
apiVersion: v1
kind: Secret
stringData:
  username: fake-username
metadata:
  name: my-username