apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: generate-docker-registry-secret
spec:
  type: dockerconfigjson
  secretName: gen-docker-registry-secret
  request:
    imageCredentials:
      username:
        key: username
        name: my-username
      password:
        key: password
        name: my-password
      registry: my-registry
      email: fake-email
---
apiVersion: v1
kind: Secret
stringData:
  username: fake-username
metadata:
  name: my-username
---
apiVersion: v1
kind: Secret
stringData:
  password: fake-password
metadata:
  name: my-password
