apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: generate-docker-registry-secret
spec:
  type: dockerconfigjson
  secretName: gen-docker-registry-secret
  imageCredentials:
    registry: fake-registry
    username: fake-username
    password: fake-password
    email: fake-email
