apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: example.quarks.tls
spec:
  request:
    certificate:
      CAKeyRef:
        key: private_key
        name: example.secret.ca
      CARef:
        key: certificate
        name: example.secret.ca
      alternativeNames: null
      commonName: kubeTlsTypeCert
      isCA: false
      signerType: local
  secretName: example.secret.tls
  type: tls
